name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "deploy-gitactions" ]
  pull_request:
    branches: [ "deploy-gitactions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  imagenfront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Frontend.
        run: docker build -t alepellereca/imagenfront:2 .
      - name: Push frontend.
        run: docker push alepellereca/imagenfront:2
  imagenback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend.
        run: docker build -t alepellereca/imagenback:2 .
      - name: Push backend.
        run: docker push alepellereca/imagenback:2